### ISSUE TITLE
How about the training time?

### ISSUE THREAD

**Issue by curiosity654** [leosampaio/sketchformer#4]
Hi, thanks for the nice work. I have a question about the network's training GPU and time consumption. The network needs 2.5M pics to train, so how much GPU memory will it take?

**Comment by leosampaio** [comment]
Hi, it has been a while since we've trained a Sketchformer, but at the time of publishing we trained it on a single Nvidia GeForce 1080 Ti (it has 12GB of VRAM), and training took less than a day. If you don't meet those requirements, try lowering the batch size since that will have the biggest impact on VRAM usage; the number of images in the training set only influences how long we'll take to go through all of them (for each epoch).

**Comment by curiosity654** [comment]
Thank you so much! I think that's quite efficient for a transformer network.
